simulatorXPP.ClassSimulatorXPP Class Reference
Public Member Functions
 __init__ (self)
 callSolver (self, outputfiles)
 createInput (self, metamodel, model, outputfiles)
 createOutputs (self, model, outputfiles, metamodel)
Private Member Functions
 __checkNames (self, model)
Detailed Description
Class for the XPP-AUT simulator.
Constructor & Destructor Documentation
__init__()
simulatorXPP.ClassSimulatorXPP.__init__ (self)
The constructor.
Member Function Documentation
__checkNames()
simulatorXPP.ClassSimulatorXPP.__checkNames (self, model) [private]
        XPPAUT converts all the strings into capittal letters, so we need to check for repeated nodes.
Referenced by simulatorXPP.ClassSimulatorXPP.createInput().
callSolver()
simulatorXPP.ClassSimulatorXPP.callSolver (self, outputfiles)
This method calls xppaut to simulate the model
createInput()
simulatorXPP.ClassSimulatorXPP.createInput (self, metamodel, model, outputfiles)
This method creates the input file for the XPPAUT simulator.
References simulatorXPP.ClassSimulatorXPP.__checkNames(), and formulas.writeXPPFormula().
createOutputs()
simulatorXPP.ClassSimulatorXPP.createOutputs (self, model, outputfiles, metamodel)
This method converts the format of the XPP output file into a more adequate for ByoDyn.
The documentation for this class was generated from the following file:
 simulatorXPP.py