simulatorOpenModelica.ClassSimulatorOpenModelica Class Reference
Public Member Functions
 __init__ (self)
 callSolver (self, outputfiles)
 createInput (self, metamodel, model, outputfiles)
 createOutputs (self, model, outputfiles, metamodel)
Private Member Functions
 __writeModel (self, model, metamodel, outputfiles)
 __writeRunner (self, metamodel, model, outputfiles)
Detailed Description
Class for the OpenModelica simulator.
Constructor & Destructor Documentation
__init__()
simulatorOpenModelica.ClassSimulatorOpenModelica.__init__ (self)
The constructor.
Member Function Documentation
__writeModel()
simulatorOpenModelica.ClassSimulatorOpenModelica.__writeModel (self, model, metamodel, outputfiles) [private]
This method writes the openModelica model file.
References formulas.writeOpenModelicaFormula().
Referenced by simulatorOpenModelica.ClassSimulatorOpenModelica.createInput().
__writeRunner()
simulatorOpenModelica.ClassSimulatorOpenModelica.__writeRunner (self, metamodel, model, outputfiles) [private]
        This method writes the openModelica options file.
Referenced by simulatorOpenModelica.ClassSimulatorOpenModelica.createInput().
callSolver()
simulatorOpenModelica.ClassSimulatorOpenModelica.callSolver (self, outputfiles)
This method calls openModelica to simulate the model
createInput()
simulatorOpenModelica.ClassSimulatorOpenModelica.createInput (self, metamodel, model, outputfiles)
        This method creates the input files for the openModelica simulator.
References simulatorOpenModelica.ClassSimulatorOpenModelica.__writeModel(), and simulatorOpenModelica.ClassSimulatorOpenModelica.__writeRunner().
createOutputs()
simulatorOpenModelica.ClassSimulatorOpenModelica.createOutputs (self, model, outputfiles, metamodel)
This method converts the format of the openModelica output file into a more adequate for ByoDyn.
The documentation for this class was generated from the following file:
 simulatorOpenModelica.py