centralFunctions Namespace Reference
Functions
 callingOctave (outputfiles)
 callingPython (outputfiles)
 createInputOctave (metamodel, model, outputfiles)
 createInputPython (metamodel, model, outputfiles)
 createOctaveOutputs (model, metamodel, outputfiles)
 matlabIntegrator (metamodel, model, outputfiles)
 neighboursFinder (model, cellIndex)
 octaveIntegration (metamodel, model, outputfiles)
 pythonIntegration (metamodel, model, outputfiles)
 writeFormulaOctave (model, node, octave, option, cellIndex)
 writeInitialConditionsOctave (model, metamodel, octave, function)
 writeParametersOctave (model, octave)
Function Documentation
callingOctave()
centralFunctions.callingOctave (outputfiles)
This function calls Octave to integrate the system of equations of the model. 
The system has been written in a file with the Octave format. 
Referenced by octaveIntegration().
callingPython()
centralFunctions.callingPython (outputfiles)
This function calls Python to integrate the system of equations of the model.
The system has been written in a file with Python format. 
Referenced by pythonIntegration().
createInputOctave()
centralFunctions.createInputOctave (metamodel, model, outputfiles)
This function creates the input file for the Octave integration. 
References formulas.readWriteFormula(), writeFormulaOctave(), writeInitialConditionsOctave(), and writeParametersOctave().
Referenced by octaveIntegration().
createInputPython()
centralFunctions.createInputPython (metamodel, model, outputfiles)
This function creates the input file for the Python integration. 
Referenced by pythonIntegration().
createOctaveOutputs()
centralFunctions.createOctaveOutputs (model, metamodel, outputfiles)
This function merges the Octave outputs and sets the header of the file consisting on the model nodes and the model rules.
Referenced by octaveIntegration().
matlabIntegrator()
centralFunctions.matlabIntegrator (metamodel, model, outputfiles)
This function is under construction.
Referenced by simulator.central().
neighboursFinder()
centralFunctions.neighboursFinder (model, cellIndex)
This function determines the cell neighbour nodes of a given node. 
The system needs to be multicellular.
Referenced by affectors.complexExtraBack(), affectors.complexExtraFwd(), affectors.dissociationExtraBack(), affectors.dissociationExtraFwd(), affectors.NonDimBindingDegradation(), and affectors.NonDimTranslationDegradationBinding().
octaveIntegration()
centralFunctions.octaveIntegration (metamodel, model, outputfiles)
This function directs the main steps to simulate the system using Octave as the integrator. 
References callingOctave(), createInputOctave(), and createOctaveOutputs().
Referenced by simulator.central(), simulator.obtainSimulationValues(), dynamicsReconstructer.run(), and optimiser.scoreObtainer().
pythonIntegration()
centralFunctions.pythonIntegration (metamodel, model, outputfiles)
This function directs the main steps to simulate the system using SciPy as the integrator.
References callingPython(), and createInputPython().
Referenced by simulator.central(), simulator.eventsDealer(), simulator.obtainSimulationValues(), dynamicsReconstructer.run(), and optimiser.scoreObtainer().
writeFormulaOctave()
centralFunctions.writeFormulaOctave (model, node, octave, option, cellIndex)
This function calls to the different functions of the module affectors from the lib directory.
Each affector writes the specific formula.
There is a general function for the SBML files.
Referenced by createInputOctave().
writeInitialConditionsOctave()
centralFunctions.writeInitialConditionsOctave (model, metamodel, octave, function)
This function writes the initial conditions for the octave option.
It takes into account the model rules for the non constant parameters and the non constant compartments.
It also writes down the integration time and time step.
Referenced by createInputOctave().
writeParametersOctave()
centralFunctions.writeParametersOctave (model, octave)
This function sets the parameters values for the octave input file.
It also takes into account the compartment values as plausible parameters of the model as they are commonly used as a parameter of the system of equations.
Referenced by createInputOctave().