starter Namespace Reference
Classes
class ClassMetaModel
Functions
 central (runnerFile)
 fortranModulesCreator (metamodel)
 incompatibilityChecker (metamodel)
Function Documentation
central()
starter.central (runnerFile)
This function directs the reading of the running options of ByoDyn.
Then it checks for incompatibilities.
References fortranModulesCreator(), and incompatibilityChecker().
Referenced by central.optionReader().
fortranModulesCreator()
starter.fortranModulesCreator (metamodel)
This function builds a module that can be called from Python from Fortran.
It must be compiled now because there are some functions that are static and some arguments have to be declared before compilation.
Referenced by central().
incompatibilityChecker()
starter.incompatibilityChecker (metamodel)
This function checks that the options of the metamodel do not contain incompatibilities.
Referenced by central().