simulator Namespace Reference
Classes
class ClassEpithelium
Functions
 central (metamodel, model, outputfiles)
 checkResults (metamodel, trajectoriesFile)
 compatibilityChecker (metamodel, model)
 createEpiplot (model, metamodel, outputfiles)
 createGnuplot (model, metamodel, outputfiles, type)
 createPDFFormulae (model, metamodel, outputfiles)
 eventsDealer (metamodel, model, outputfiles)
 flatFileWriter (outputfiles, grid)
 isAGene (node)
 lastStateRetriever (metamodel, model, outputfiles)
 obtainSimulationValues (metamodel, model, outputfiles, type)
 plotMaker (outputfiles, grid, model)
 setIntegrationOption (model, tester)
Function Documentation
central()
simulator.central (metamodel, model, outputfiles)
This function controls the flow of the simulation depending on the simulation options.
It checks the correctness of the input data, 
it creates a pdf format file with the system of equations, 
it integrates the system with the selected integrator and
it finally builds the graphs of the simulation.
References checkResults(), compatibilityChecker(), createEpiplot(), createGnuplot(), createPDFFormulae(), eventsDealer(), centralFunctions.matlabIntegrator(), centralFunctions.octaveIntegration(), centralFunctions.pythonIntegration(), and setIntegrationOption().
Referenced by central.runner().
checkResults()
simulator.checkResults (metamodel, trajectoriesFile)
This function checks the integration output file. 
It returns an error if the results are missing and a warning if the results are incomplete.
Referenced by central().
compatibilityChecker()
simulator.compatibilityChecker (metamodel, model)
This function checks the compatibility of some simulation options:
if the model holds events has to be integrated by OpenModelica and
that a certain parameter of the model exists for which its value is specified.
Referenced by central(), fitnessFunctionEvaluator.central(), and sampler.central().
createEpiplot()
simulator.createEpiplot (model, metamodel, outputfiles)
This function creates the multicellular plots.
It calls the class ClassEpithelium, fills the object
and creates a flat file data and the graph.
References flatFileWriter(), and plotMaker().
Referenced by central().
createGnuplot()
simulator.createGnuplot (model, metamodel, outputfiles, type)
This function creates the postscript plots for the dynamic trajectories.
It is responsible for the plotting of both the concentration versus time plots
and the change of concentration versus time plots.
Referenced by central(), and obtainSimulationValues().
createPDFFormulae()
simulator.createPDFFormulae (model, metamodel, outputfiles)
This function creates the latex format files with the system of equations. 
It calls the different affector functions at the affectors module of the lib directory.
References formulas.formulaLatex(), and formulas.getMathExpression().
Referenced by central().
eventsDealer()
simulator.eventsDealer (metamodel, model, outputfiles)
This function simulates the model in the case it holds events.
It runs the different simulations depending on the number of events and
it joins them finally.
References lastStateRetriever(), and centralFunctions.pythonIntegration().
Referenced by central().
flatFileWriter()
simulator.flatFileWriter (outputfiles, grid)
This function writes a flat file with the information of the ClassEpithelium.
Referenced by createEpiplot().
isAGene()
simulator.isAGene (node)
This function returns a boolean determining if the node is or not a gene.
The function's answer is based on whether the first character of the string is capital or not.
This function is only used to determine the font of the node at the multicellular plot.
lastStateRetriever()
simulator.lastStateRetriever (metamodel, model, outputfiles)
This function returns the values of the nodes at the last time of the simulation.
Referenced by eventsDealer().
obtainSimulationValues()
simulator.obtainSimulationValues (metamodel, model, outputfiles, type)
This function obtains the simulation values of a given model.
It is used by the optimiser and the sensitivityAnalyzer modules.
References createGnuplot(), parallel.currentProcessor(), centralFunctions.octaveIntegration(), centralFunctions.pythonIntegration(), and setIntegrationOption().
Referenced by sensitivityAnalyzer.ClassSensitivityAnalyzer.calculateSens().
plotMaker()
simulator.plotMaker (outputfiles, grid, model)
This function creates the postscript files for the multicellular plots.
Referenced by createEpiplot().
setIntegrationOption()
simulator.setIntegrationOption (model, tester)
This function set the integration option depending of model characteristics
and the software installed on the current machine. 
Referenced by central(), obtainSimulationValues(), dynamicsReconstructer.run(), and optimiser.scoreObtainer().