sampler Namespace Reference
Classes
class ClassSample
class ClassSamplerMonteCarlo
Functions
 central (model, metamodel, outputfiles)
 plot1D (metamodel, outputfiles, sample)
 plot2D (metamodel, outputfiles, sample)
 plot3D (metamodel, outputfiles, sample)
 plotResults (metamodel, outputfiles, sample)
 rainbowColourCalculator (value)
 storeResults (listOfSample, file, metamodel)
Function Documentation
central()
sampler.central (model, metamodel, outputfiles)
This is the central function of the module.
It directs the flow of the Monte Carlo sampling depending on the options.
References optimiser.checkDataPoints(), optimiser.checkParametersToVary(), optimiser.checkTargetNodes(), simulator.compatibilityChecker(), plotResults(), and storeResults().
Referenced by central.runner().
plot1D()
sampler.plot1D (metamodel, outputfiles, sample)
This function creates a histogram of the distribution of the accepted sampled points.
Referenced by plotResults().
plot2D()
sampler.plot2D (metamodel, outputfiles, sample)
This function plots a 2D graphs with the accepted sampled points.
References rainbowColourCalculator().
Referenced by plotResults().
plot3D()
sampler.plot3D (metamodel, outputfiles, sample)
This function creates a gnuplot script to plot in 3D the Monte Carlo results.
Referenced by plotResults().
plotResults()
sampler.plotResults (metamodel, outputfiles, sample)
This function creates a 1D, 2D or 3D graphs if the parameter space is 1, 2 or 3 dimensional.
Otherwise it gives a message expressing the impossibility of the graph.
References plot1D(), plot2D(), and plot3D().
Referenced by central().
rainbowColourCalculator()
sampler.rainbowColourCalculator (value)
Given a normalised value on the 0-4 range, this function returns the corresponding RGB colour code based on the rainbow scale. 
Referenced by plot2D().
storeResults()
sampler.storeResults (listOfSample, file, metamodel)
This method stores the sampling solution on its specific file.
Referenced by central().