sensitivityAnalyzer Namespace Reference
Classes
class ClassSensitivityAnalyzer
Functions
 central (model, metamodel, outputfiles)
 componentsChecker (model, metamodel)
 getNodeName (value, model)
 getPositionNode (field, model)
Function Documentation
central()
sensitivityAnalyzer.central (model, metamodel, outputfiles)
This is the central function of the module.
It directs the flow of the program for the sensitivity analysis and the identifiability analysis.
References componentsChecker().
Referenced by central.runner().
componentsChecker()
sensitivityAnalyzer.componentsChecker (model, metamodel)
This function is an initial checking of the parameters we want to study:
first that they exist on the model and second that they are constant during the simulation.
Finally we select the parameters to study on a new working variable.
At the very end we set the new parameters values set by "parameter" variable.
Referenced by identifiabilityAnalyzer.central(), optimalExperimentalDesign.central(), and central().
getNodeName()
sensitivityAnalyzer.getNodeName (value, model)
Given the position of a node in model.nodes list
this function returns its name. 
In the case of multicellular models the index positions
are added in the format: "nodeName(yindex,xindex)".
Referenced by sensitivityAnalyzer.ClassSensitivityAnalyzer.__obtainSensitivity().
getPositionNode()
sensitivityAnalyzer.getPositionNode (field, model)
Given a target field ("node/xindex,yindex/experimentalValue/variance"),
this function returns the column position of this node 
in the simulation output file.
Referenced by sensitivityAnalyzer.ClassSensitivityAnalyzer.__obtainSensitivity().