surface Namespace Reference
Functions
 central (metamodel, model, outputfiles)
 checkSurfaceParameters (metamodel, model)
 rainbowColorCalculation (value, minValue, maxValue)
 surfacePlotter (metamodel, outputfiles, plot, surface, xGrid, yGrid)
 surfaceTextSaver (outputfiles, metamodel, plot, surface)
Function Documentation
central()
surface.central (metamodel, model, outputfiles)
This function directs the creation of the surface of fitness function values.
It checks that the selected parameters are in model.
It variates the parameters and calls the scoreObtainer function from the 
Optimiser module to calculate the fitness function value.
References checkSurfaceParameters(), optimiser.scoreObtainer(), surfacePlotter(), and surfaceTextSaver().
Referenced by central.runner().
checkSurfaceParameters()
surface.checkSurfaceParameters (metamodel, model)
This function checks that the selected parameters for the surface plot do exist in the model.
Referenced by central().
rainbowColorCalculation()
surface.rainbowColorCalculation (value, minValue, maxValue)
This function calculates the color based on a rainbow scale
Referenced by surfacePlotter().
surfacePlotter()
surface.surfacePlotter (metamodel, outputfiles, plot, surface, xGrid, yGrid)
This function creates the postscript surface plot.
References rainbowColorCalculation().
Referenced by central().
surfaceTextSaver()
surface.surfaceTextSaver (outputfiles, metamodel, plot, surface)
This function writes in a text file the results of the fitness function evaluation along the grid.
Referenced by central().