parallel Namespace Reference
Functions
 currentProcessor ()
 mainProcessor ()
 receive (Source, Tag)
 receiveAny (Tag)
 runsOnParallelMachine ()
 send (Object, Destination, Tag)
 sendAll (Object, Tag)
 totalProcessors ()
 waitProcessors ()
Variables
 communicator = None
dict internalBuffer = {}
Function Documentation
currentProcessor()
parallel.currentProcessor ()
This function provides which is the current processor.
It returns an integer.
Referenced by optimiser.gaPopulationScoresObtainer(), simulator.obtainSimulationValues(), and central.runner().
mainProcessor()
parallel.mainProcessor ()
This function discriminates if the current processor is the main processor, that is, processor 0
It returns a boolean variable.
Referenced by optimiser.central(), optimiser.gaPopulationScoresObtainer(), initiator.initial(), central.main(), and central.runner().
receive()
parallel.receive (Source, Tag)
This function receives an object from a determined processor.
It takes as arguments:
Source, the source processor, and
Tag, an aditional identifier of the object.
It returns the object.
Referenced by optimiser.gaPopulationScoresObtainer().
receiveAny()
parallel.receiveAny (Tag)
This function receives an object from any processor.
It takes as argument, Tag, an aditional identifier of the object.
It returns the object.
Referenced by optimiser.central(), optimiser.gaPopulationScoresObtainer(), initiator.initial(), central.main(), and central.runner().
runsOnParallelMachine()
parallel.runsOnParallelMachine ()
This function determines if the program runs in parallel or serial environment.
It returns a boolean variable.
send()
parallel.send (Object, Destination, Tag)
This function sends an object to a defined processor.
It takes as arguments:
Object, the object, 
Destination, the destination processor, and
Tag, an aditional identifier of the object.
It returns nothing.
Referenced by optimiser.gaPopulationScoresObtainer().
sendAll()
parallel.sendAll (Object, Tag)
This function send a given object to all processors.
It takes as arguments:
Object, the object to be sent, and
Tag, an aditional identifier of the object.
It returns nothing.
Referenced by optimiser.central(), optimiser.gaPopulationScoresObtainer(), initiator.initial(), central.main(), and central.runner().
totalProcessors()
parallel.totalProcessors ()
This function provides the amount of processors.
It returns an integer.
Referenced by optimiser.gaPopulationScoresObtainer().
waitProcessors()
parallel.waitProcessors ()
This function makes all the processors to wait up to that point.
Variable Documentation
communicator
parallel.communicator = None
internalBuffer
dict parallel.internalBuffer = {}