sbmlWorker Namespace Reference
Classes
class ClassEvent
class ClassFunction
class ClassModelSBML
class ClassReaction
class ClassRules
Functions
 divCompartment (sbmlModel, formula, node)
 getBooleanExpression (ASTNode)
 sbmlWriter (w, model, metamodel, file)
 translateLocalParametersNamesInFormula (formula, reaction)
 translateMathFactor (mathFactor)
Function Documentation
divCompartment()
sbmlWorker.divCompartment (sbmlModel, formula, node)
This function divides the formula by compartment volume if it is needed.
Referenced by sbmlWorker.ClassModelSBML.__readTopology().
getBooleanExpression()
sbmlWorker.getBooleanExpression (ASTNode)
This function reads an ASTNode (equation in Abstract Syntax Tree class)
and builds the equation as a math string using recursive calls.
It returns the math string and the operator.
References getBooleanExpression(), and translateMathFactor().
Referenced by sbmlWorker.ClassModelSBML.__readEvents(), and getBooleanExpression().
sbmlWriter()
sbmlWorker.sbmlWriter (w, model, metamodel, file)
This function writes a SBML model given the object model.
Referenced by exporter.central(), optimiser.evaluateSolution(), localOptimiser.savingResults(), and optimiser.storeSolution().
translateLocalParametersNamesInFormula()
sbmlWorker.translateLocalParametersNamesInFormula (formula, reaction)
This function replaces in a formula all the names of parameters,
because we need convert the local paramters to a new format ('parameterId''ReactionId')
in order to work correctly with SBML definition of parameters
where the local and global parameters can have the same ids.
Referenced by sbmlWorker.ClassModelSBML.__readTopology().
translateMathFactor()
sbmlWorker.translateMathFactor (mathFactor)
This function converts some string logical affectors to Open Modelica format.
Referenced by getBooleanExpression().