initiator Namespace Reference
Functions
 createExamples ()
 initial (runnerFile=None)
 printingHelp ()
 printingVersion (version)
 versionDefinitor ()
Variables
str benchmarkdir = os.environ.get('BYODYN_PATH') + '/benchmark'
str libdir = os.environ.get('BYODYN_PATH') + '/lib'
str srcdir = os.environ.get('BYODYN_PATH') + '/src'
Function Documentation
createExamples()
initiator.createExamples ()
The function creates the examples of ByoDyn at the examples directory. 
Referenced by initial().
initial()
initiator.initial (runnerFile = None)
This function reads the command line options, it configures the ByoDyn options and checks its consistency and calls the modules of the source directory of ByoDyn. 
References createExamples(), checker.main(), central.main(), parallel.mainProcessor(), printingHelp(), printingVersion(), parallel.receiveAny(), parallel.sendAll(), and versionDefinitor().
printingHelp()
initiator.printingHelp ()
This function prints the command line help. 
Referenced by initial().
printingVersion()
initiator.printingVersion (version)
This function prints the current ByoDyn version. 
Referenced by initial().
versionDefinitor()
initiator.versionDefinitor ()
This funciton defines the ByoDyn version globally.
Referenced by initial().
Variable Documentation
benchmarkdir
str initiator.benchmarkdir = os.environ.get('BYODYN_PATH') + '/benchmark'
libdir
str initiator.libdir = os.environ.get('BYODYN_PATH') + '/lib'
srcdir
str initiator.srcdir = os.environ.get('BYODYN_PATH') + '/src'