formulas Namespace Reference
Functions
 checkBrackets (formula)
 formatPowers (formula, option)
 formulaLatex (xmlFormula, file, model)
 getMathExpression (ASTNode)
 includeFunctions (model, formula)
 piecewise (a, b, c)
 readWriteFormula (model, file, cellIndex, option, formula)
 replaceConstants (model, constant)
 solveFormula (model, formula)
 translateMathFactor (mathFactor)
 writeOpenModelicaFormula (formula, file)
 writeXPPFormula (formula, file)
Function Documentation
checkBrackets()
formulas.checkBrackets (formula)
This function checks if the use of brackets is correct in a math expression.
It returns the formula modified if the number of brackets is not correct and prints a warning in the standard output.
Referenced by readWriteFormula(), solveFormula(), and writeOpenModelicaFormula().
formatPowers()
formulas.formatPowers (formula, option)
This function checks for the powers and it substitute 'pow(k, n)' to 'k**n'.
References formatPowers().
Referenced by formatPowers().
formulaLatex()
formulas.formulaLatex (xmlFormula, file, model)
This function converts the MathML of SBML into latex format.
References getMathExpression().
Referenced by simulator.createPDFFormulae(), and affectors.SBML().
getMathExpression()
formulas.getMathExpression (ASTNode)
This function return a string with the math expression in latex syntax and the operator of a ASTNode.
ASTNode is a object codifying a formula using a abstract syntax tree object.
It does recursive calls to itself in order to build the math expression.
References getMathExpression(), and translateMathFactor().
Referenced by simulator.createPDFFormulae(), formulaLatex(), and getMathExpression().
includeFunctions()
formulas.includeFunctions (model, formula)
This function get a formula and return a new formula without external functions used.
A external function is a non-python function like the user-defined functions in SBML. 
It replaces the function definitions with the function output in order to create a string without external functions.
References includeFunctions().
Referenced by includeFunctions(), and solveFormula().
piecewise()
formulas.piecewise (a, b, c)
This function converts the format of piecewise function in MathML to the piecewise function in Scipy. 
readWriteFormula()
formulas.readWriteFormula (model, file, cellIndex, option, formula)
This funtion inputs the SBML string of the formula and writes out on Python or Octave formats.
References checkBrackets().
Referenced by centralFunctions.createInputOctave(), and affectors.SBML().
replaceConstants()
formulas.replaceConstants (model, constant)
This functions replaces a parameter for its value or a variable for its initial condition value.
Referenced by solveFormula().
solveFormula()
formulas.solveFormula (model, formula)
This function evaluates a algebraic string, replacing all the parameters and variables for its values in time 0 and returns the value.
References checkBrackets(), includeFunctions(), and replaceConstants().
Referenced by sbmlWorker.ClassModelSBML.__searchDelayFunction(), and sbmlWorker.ClassModelSBML.checkAssignmentRule().
translateMathFactor()
formulas.translateMathFactor (mathFactor)
This function converts operators to python format.
Referenced by getMathExpression().
writeOpenModelicaFormula()
formulas.writeOpenModelicaFormula (formula, file)
This function inputs the SBML string of the formula and writes out on OpenModelica format.
References checkBrackets().
Referenced by simulatorOpenModelica.ClassSimulatorOpenModelica.__writeModel(), and affectors.SBML().
writeXPPFormula()
formulas.writeXPPFormula (formula, file)
This function inputs the SBML string of the formula and writes out on XPP format.
Referenced by simulatorXPP.ClassSimulatorXPP.createInput(), and affectors.SBML().