dynamicsReconstructer Namespace Reference
Functions
 central (metamodel, model, outputfiles)
 initialConditionsDetector (metamodel, model)
 modelDetermination (model, simulation, solutions, initialConditions)
 parametersDetector (metamodel, model)
 plotter (solutions, model, outputfiles, metamodel)
 run (model, metamodel, outputfiles)
 runner (metamodel, model, outputfiles, solutions, initialConditions)
 storeInfo (outputfiles, simulation, model)
Function Documentation
central()
dynamicsReconstructer.central (metamodel, model, outputfiles)
This is the central function of the module.
It checks that the parameters introduced are correct, reads the solutions and runs the model.
References initialConditionsDetector(), parametersDetector(), plotter(), and runner().
Referenced by central.runner().
initialConditionsDetector()
dynamicsReconstructer.initialConditionsDetector (metamodel, model)
This function checks for the solutions of the initial conditions in case of
Referenced by central().
modelDetermination()
dynamicsReconstructer.modelDetermination (model, simulation, solutions, initialConditions)
This function sets the model parameter values.
Referenced by runner().
parametersDetector()
dynamicsReconstructer.parametersDetector (metamodel, model)
This function checks that the parameters' solutions' files located at the solutionsDirectory are part of the model.
Referenced by central().
plotter()
dynamicsReconstructer.plotter (solutions, model, outputfiles, metamodel)
This function plots the reconstructed trajectories.
Referenced by central().
run()
dynamicsReconstructer.run (model, metamodel, outputfiles)
This function calls the model integrators to render the dynamics.
References centralFunctions.octaveIntegration(), centralFunctions.pythonIntegration(), and simulator.setIntegrationOption().
Referenced by runner().
runner()
dynamicsReconstructer.runner (metamodel, model, outputfiles, solutions, initialConditions)
This function, for each solution,  creates and simulates the corresponding model and stores the dynamics.
References modelDetermination(), run(), and storeInfo().
Referenced by central().
storeInfo()
dynamicsReconstructer.storeInfo (outputfiles, simulation, model)
This function stores the dynamics of the solutions.
It creates a file for each node of the system.
Referenced by runner().