localOptimiser Namespace Reference
Functions
 central (model, metamodel, outputfiles)
 globalDefiner (model, metamodel, outputfiles)
 locatingModuleDir (metamodel)
 optimisation (threshold)
 pcalcr (x, p)
 savingResults (value, model, metamodel, outputfiles)
Function Documentation
central()
localOptimiser.central (model, metamodel, outputfiles)
This is the main function of the module.
First it appends the compiling directory to the system path.
Then it makes global the three main objects of the program (model, metamodel and outputfiles) and the module localSearch.
It calls the optimisation routine, obtains the new value of the parameters and the fitness function value.
It updates the model and sends the very last fitness function.
References globalDefiner(), optimisation(), and savingResults().
Referenced by optimiser.central(), optimiser.evaluateSolution(), and optimiser.gaPopulationScoresObtainerLocal().
globalDefiner()
localOptimiser.globalDefiner (model, metamodel, outputfiles)
This function adds the compilation directory to the system path.
Then it makes global the model, metamodel and outputfiles objects and the localSearch fortran function.
It finally defines the metamodel.hybridScore variable as True for the correct calculation of the score: the Fortran function returns a list and Python functions work with a float.
References locatingModuleDir().
Referenced by central().
locatingModuleDir()
localOptimiser.locatingModuleDir (metamodel)
This function appends the compiling directory to the system path.
Referenced by globalDefiner().
optimisation()
localOptimiser.optimisation (threshold)
This function interacts with the Fortran code directly.
It calls the main routine of the Fortran program.
It sends the variables: x for the parameter values and b for the parameter ranges. And optionally it can send the value for the stopper threshold (v31).
Finally it collects the optimised parameter vector and the fitness function value.
Referenced by central().
pcalcr()
localOptimiser.pcalcr (x, p)
This function is called by the Fortran program localSearch.
This function obtains the fitness function value for the new parameter position given by the Fortran program.
References optimiser.scoreObtainer().
savingResults()
localOptimiser.savingResults (value, model, metamodel, outputfiles)
This function saves the results of the local optimisation.
References sbmlWorker.sbmlWriter().
Referenced by central().