optimalExperimentalDesign Namespace Reference
Functions
 addNewPoint (identifiability, sensitivity, metamodel, model, outputfiles, parametersToStudy)
 central (model, metamodel, outputfiles)
 chooseValue (criteria, values)
 getCriteria (criteria, identifiability)
 rankTargets (identifiability, sensitivity, metamodel, model, outputfiles, parametersToStudy)
 timePointsDeterminer (metamodel)
Function Documentation
addNewPoint()
optimalExperimentalDesign.addNewPoint (identifiability, sensitivity, metamodel, model, outputfiles, parametersToStudy)
This function runs the addNewPoint optimal experimental design protocol.
In this task we evaluate the criteria value at different timePoints after adding a putative target of the given species at that specific time point. 
We can also run the protocol for a list of species.  
References chooseValue(), getCriteria(), and timePointsDeterminer().
Referenced by central().
central()
optimalExperimentalDesign.central (model, metamodel, outputfiles)
This is the central function of the module.
It directs the flow of the program for the optimal experimental design.
References addNewPoint(), sensitivityAnalyzer.componentsChecker(), and rankTargets().
Referenced by central.runner().
chooseValue()
optimalExperimentalDesign.chooseValue (criteria, values)
This function returns the maximmum or minimmun value of values lists depending on the criteria type. 
Referenced by addNewPoint().
getCriteria()
optimalExperimentalDesign.getCriteria (criteria, identifiability)
This function returns the criteria value specified by the user in runner. 
Referenced by addNewPoint(), and rankTargets().
rankTargets()
optimalExperimentalDesign.rankTargets (identifiability, sensitivity, metamodel, model, outputfiles, parametersToStudy)
This function is still in development status. It sorts of targets indicating the more and the less important. 
Less important means with low effect to improve the identifiability criteria.
References getCriteria().
Referenced by central().
timePointsDeterminer()
optimalExperimentalDesign.timePointsDeterminer (metamodel)
This function returns the time points of study of the optimal experimental design.
It is based on the metamodel arguments of time&timestep and OEDResolution.
Referenced by addNewPoint().