central Namespace Reference
Classes
class ClassFile
Functions
 main (runnerFile)
Main Program #.
 modelReader (metamodel)
Main Functions #
 optionReader (runnerFile)
 profile ()
 runner (metamodel, model)
 sbmlReader (metamodel)
 tagsReader (metamodel)
Function Documentation
main()
central.main (runnerFile)
Main Program #.
This is the main function of the entire program.
It builds an object called "metamodel" with the options to run ByoDyn, another object called "model" with the structure of the system and finally the function calls the function "runner" to execute the instructions. 
References main(), parallel.mainProcessor(), modelReader(), optionReader(), parallel.receiveAny(), runner(), and parallel.sendAll().
Referenced by testers.ClassTest.__execute(), initiator.initial(), and main().
modelReader()
central.modelReader (metamodel)
Main Functions #
This function reads the model file (the name of the file is inside the metamodel object) and creates a model object with the model information and details. 
It works for either formats, "tags" or "SBML". 
References sbmlReader(), and tagsReader().
Referenced by main().
optionReader()
central.optionReader (runnerFile)
This function reads the runner file of ByoDyn and creates the metamodel object that contains its information. 
References starter.central().
Referenced by main().
profile()
central.profile ()
This function determines the number of times ByoDyn is run for profiling. 
runner()
central.runner (metamodel, model)
This function discriminates the different main running options of ByoDyn and calls its appropiate functions. 
The different possibilities are simulation, parameter estimation, sensitivity analysis, model format exporting, simulation trajectories reconstruction from a given parameter value set, creation of score surfaces of the fitness with respect of the vector of parameters and fitness function evaluation. 
References dynamicsReconstructer.central(), exporter.central(), simulator.central(), surface.central(), optimiser.central(), fitnessFunctionEvaluator.central(), identifiabilityAnalyzer.central(), optimalExperimentalDesign.central(), sampler.central(), sensitivityAnalyzer.central(), parallel.currentProcessor(), cluster.main(), parallel.mainProcessor(), parallel.receiveAny(), and parallel.sendAll().
Referenced by main().
sbmlReader()
central.sbmlReader (metamodel)
This function reads a model in SBML format and create the model object. 
Referenced by modelReader().
tagsReader()
central.tagsReader (metamodel)
This function reads the model in "tags" format and creates the model object. 
Referenced by modelReader().