affectors Namespace Reference
Functions
 complexExtraBack (model, file, option, cellIndex, definition, fieldsDefinition)
 complexExtraFwd (model, file, option, cellIndex, definition, fieldsDefinition)
 constant (model, file, option, cellIndex, definition, fieldsDefinition)
 constitutive (model, file, option, cellIndex, definition, fieldsDefinition)
 degradation (model, file, option, cellIndex, definition, fieldsDefinition)
 dissociationExtraBack (model, file, option, cellIndex, definition, fieldsDefinition)
 dissociationExtraFwd (model, file, option, cellIndex, definition, fieldsDefinition)
 inhibition (model, file, option, cellIndex, definition, fieldsDefinition)
 NonDimBindingDegradation (model, file, option, cellIndex, definition, fieldsDefinition)
 NonDimConstitutiveDegradation (model, file, option, cellIndex, definition, fieldsDefinition)
From here below, non dimension affectors.
 NonDimInhibitionDegradation (model, file, option, cellIndex, definition, fieldsDefinition)
 NonDimTranscriptionDegradation (model, file, option, cellIndex, definition, fieldsDefinition)
 NonDimTranslationDegradation (model, file, option, cellIndex, definition, fieldsDefinition)
 NonDimTranslationDegradationBinding (model, file, option, cellIndex, definition, fieldsDefinition)
 SBML (model, file, option, cellIndex, definition, fieldsDefinition)
 transcription (model, file, option, cellIndex, definition, fieldsDefinition)
 translation (model, file, option, cellIndex, definition, fieldsDefinition)
Function Documentation
complexExtraBack()
affectors.complexExtraBack (model, file, option, cellIndex, definition, fieldsDefinition)
This function writes one of the mathematical terms (the other is done by complexExtraFwd) of a biological extracellular complex formation.
This term affects the nodes defined as receptor and ligand.
d[RECEPTOR]i / dt = - 1 / 64 k_binding_RECEPTOR.LIGAND [RECEPTOR]i <Sum>(j = 1;j = k) [LIGAND]j
d[LIGAND]i / dt = - 1 / 64  k_binding_RECEPTOR.LIGAND [LIGAND]i <Sum>(j = 1;j = k) [RECEPTOR]j
References centralFunctions.neighboursFinder().
complexExtraFwd()
affectors.complexExtraFwd (model, file, option, cellIndex, definition, fieldsDefinition)
This function writes one of the mathematical terms (the other is done by complexExtraBack) of biological extracellular complex formation.
This term affects the node defined as the complex
d[COMPLEX]i / dt = +  1 / 64 * k_binding_RECEPTOR.LIGAND [RECEPTOR]i  <Sum>(j = 1;j = k) [LIGAND]j
References centralFunctions.neighboursFinder().
constant()
affectors.constant (model, file, option, cellIndex, definition, fieldsDefinition)
This function writes the mathematical term of a non changing biological node.
d [node] / dt =  0
constitutive()
affectors.constitutive (model, file, option, cellIndex, definition, fieldsDefinition)
This function writes the mathematical term of a biological constitutive expression.
d [node] / dt = constant > 0
degradation()
affectors.degradation (model, file, option, cellIndex, definition, fieldsDefinition)
This function writes the mathematical term of a biological degradation.
d [node] / dt = -k * [node]
dissociationExtraBack()
affectors.dissociationExtraBack (model, file, option, cellIndex, definition, fieldsDefinition)
This function writes one of the mathematical terms (the other is done by dissociationExtraFwd) of a biological extracellular complex dissociation.
This term affects the node defined as the complex.
d[COMPLEX]i / dt = -  1 / 8 k_dissociation_COMPLEX <Sum>(j = 1;j = k) [COMPLEX]i
References centralFunctions.neighboursFinder().
dissociationExtraFwd()
affectors.dissociationExtraFwd (model, file, option, cellIndex, definition, fieldsDefinition)
This function writes one of the mathemathical terms (the other is done by dissociationExtraFwd) of a biological extracellular complex dissociation.
This term affects the nodes defined as receptor and ligand.
The formula is different depending on being the receptor or the ligand
d[RECEPTOR]i / dt = + 1 / 8 k_dissociation_COMPLEX <Sum>(j = 1;j = k) [COMPLEX]i
d[LIGAND]i / dt = + 1/8 k_dissociation_COMPLEX <Sum>(j = 1;j = k) [COMPLEX]j
References centralFunctions.neighboursFinder().
inhibition()
affectors.inhibition (model, file, option, cellIndex, definition, fieldsDefinition)
This function writes the mathematical term of a biological inhibition.
d [PROTEIN] / dt = + k_basal / 1 + ([INHIBITOR]/k_inhibition)^s
NonDimBindingDegradation()
affectors.NonDimBindingDegradation (model, file, option, cellIndex, definition, fieldsDefinition)
This affector compiles an complex binding and a degradation.
dcomplex/dtau = (k/n^2) * k_bind [LIGAND]_0 RECEPTOR_i \sum LIGAND_j - k_deg COMPLEX_i
References centralFunctions.neighboursFinder().
NonDimConstitutiveDegradation()
affectors.NonDimConstitutiveDegradation (model, file, option, cellIndex, definition, fieldsDefinition)
From here below, non dimension affectors.
This affector compiles the constitutive gene expression and degradation.
dnode/dtau = k_deg*(rate - node)
NonDimInhibitionDegradation()
affectors.NonDimInhibitionDegradation (model, file, option, cellIndex, definition, fieldsDefinition)
This affector compiles an inhibition and a degradation.
dnode/dtau = k_deg * (1 - (INHIBITOR^m/kappa^m+INHIBITION^m) - node)
NonDimTranscriptionDegradation()
affectors.NonDimTranscriptionDegradation (model, file, option, cellIndex, definition, fieldsDefinition)
This affector compiles transcription and degradation.
dnode/dtau = k_deg(ACTIVATOR^m/(kappa^m+ACTIVATOR^m) - node)
NonDimTranslationDegradation()
affectors.NonDimTranslationDegradation (model, file, option, cellIndex, definition, fieldsDefinition)
This affector compiles translation and degradation.
dnode/dtau = k_deg(gene -PROTEIN)
NonDimTranslationDegradationBinding()
affectors.NonDimTranslationDegradationBinding (model, file, option, cellIndex, definition, fieldsDefinition)
This affector compiles the translation, degradation and ligand binding.
dNODE/dtau = k_deg(node - NODE) - (k/n^2) * k_bind [LIGAND]_0 RECEPTOR_i \sum LIGAND_j
References centralFunctions.neighboursFinder().
SBML()
affectors.SBML (model, file, option, cellIndex, definition, fieldsDefinition)
This function converts the SBML formula format into the integrators' format.
It calls different functions from the formulas module.
References formulas.formulaLatex(), formulas.readWriteFormula(), formulas.writeOpenModelicaFormula(), and formulas.writeXPPFormula().
transcription()
affectors.transcription (model, file, option, cellIndex, definition, fieldsDefinition)
This function writes the mathematical term of a biological transcription.
d[mRNA] / dt = v * [ACTIVATOR]^m / k^m + [ACTIVATOR]^m
translation()
affectors.translation (model, file, option, cellIndex, definition, fieldsDefinition)
This function writes the mathematical term of a biological translation.
d[PROTEIN] / dt = + k_translation_gene * [gene]