fitnessFunctionEvaluator Namespace Reference
Functions
 central (model, metamodel, outputfiles)
 scoreWriter (score, outputfiles)
Function Documentation
central()
fitnessFunctionEvaluator.central (model, metamodel, outputfiles)
The function checks for the compatibility of the simulation options and inserts a specified parameter value if it is the case, 
it checks that the data points correspond to the simulation time, 
it checks the target nodes and finally evaluates the fitness function.
References optimiser.checkDataPoints(), optimiser.checkTargetNodes(), simulator.compatibilityChecker(), optimiser.scoreObtainer(), and scoreWriter().
Referenced by central.runner().
scoreWriter()
fitnessFunctionEvaluator.scoreWriter (score, outputfiles)
This function writes in the log file the score obtained for the fitness function evaluation.
Referenced by central().