optimiser Namespace Reference
Functions
 calculateConfidenceIntervals (model, metamodel, outputfiles)
 central (metamodel, model, outputfiles, solutions)
 checkDataPoints (model, metamodel)
 checkInitialConditionsToVary (model, metamodel)
 checkParametersToVary (model, metamodel)
 checkTargetNodes (model, metamodel)
 evaluateIteration (karyotype, model, metamodel, outputfiles, scores, iteration)
 evaluateSolution (iteration, score, metamodel, model, outputfiles)
 evaluateStopping (metamodel, iteration, scores)
 gaInitialisePopulation (model, metamodel)
 gaNaturalSelection (karyotype, iteration, scores, metamodel, outputfiles)
 gaPopulationScoresObtainer (iteration, karyotype, metamodel, model, outputfiles)
 gaPopulationScoresObtainerLocal (iteration, karyotype, metamodel, model, outputfiles)
 gaSex (karyotype, bestChromosomes, sexChromosomes, model, metamodel)
 getSimulateValue (originalSimulationValues, node, target, model, metamodel)
 linearVariation (minimalValue, maximalValue)
 logarithmicVariation (minimalValue, maximalValue)
 normalVariationForInitialCondition (metamodel, model)
 randomSearch (metamodel, model, outputfiles)
 scoreObtainer (metamodel, model, outputfiles)
 storeSolution (score, metamodel, model, workingDirectory)
Function Documentation
calculateConfidenceIntervals()
optimiser.calculateConfidenceIntervals (model, metamodel, outputfiles)
This function calculates the covariance matrix and returns the object identifiability.
This object is necessary to calculate the confidence intervals.
The implementation of confidence intervals is still under development, not finished yet.
Referenced by evaluateSolution().
central()
optimiser.central (metamodel, model, outputfiles, solutions)
This function directs the optimisation to the different optimisation options.
References localOptimiser.central(), checkDataPoints(), checkInitialConditionsToVary(), checkParametersToVary(), checkTargetNodes(), evaluateSolution(), evaluateStopping(), gaInitialisePopulation(), gaNaturalSelection(), gaPopulationScoresObtainer(), gaPopulationScoresObtainerLocal(), gaSex(), linearVariation(), logarithmicVariation(), parallel.mainProcessor(), normalVariationForInitialCondition(), randomSearch(), parallel.receiveAny(), scoreObtainer(), and parallel.sendAll().
Referenced by central.runner().
checkDataPoints()
optimiser.checkDataPoints (model, metamodel)
This function checks for the consistency of the target.
It checks if the target constrain has a time value larger than the simulation time.
Referenced by central(), fitnessFunctionEvaluator.central(), and sampler.central().
checkInitialConditionsToVary()
optimiser.checkInitialConditionsToVary (model, metamodel)
This function checks for the consistency of the initial conditions to vary.
It checks that the values of the initial conditions are part of the nodes.
Apart it checks for incompatibilities about model boundary conditions.
Referenced by central().
checkParametersToVary()
optimiser.checkParametersToVary (model, metamodel)
This function checks for the consistency of the introduced parameters to vary:
the parameter to vary has to be one of the model's,
the parameter to vary cannot be a constant parameter and
the lower value of the exploring range has to be specified before the higher value.
Referenced by central(), and sampler.central().
checkTargetNodes()
optimiser.checkTargetNodes (model, metamodel)
This function checks that the nodes of the experimental data are part of the model.
Referenced by central(), fitnessFunctionEvaluator.central(), and sampler.central().
evaluateIteration()
optimiser.evaluateIteration (karyotype, model, metamodel, outputfiles, scores, iteration)
This function helps the evaluation of the stopping of the program.
It evaluates at the same time the stopper options and the stopper variables.
It modifies the stopper options for the proper evaluation of the stopping by evaluateStopping.
References evaluateSolution().
Referenced by gaPopulationScoresObtainer(), and gaPopulationScoresObtainerLocal().
evaluateSolution()
optimiser.evaluateSolution (iteration, score, metamodel, model, outputfiles)
This function evaluates if the solution is susceptible of being stored.
It involves the creation of solution directories and files.
References calculateConfidenceIntervals(), localOptimiser.central(), sbmlWorker.sbmlWriter(), and storeSolution().
Referenced by central(), evaluateIteration(), and gaPopulationScoresObtainer().
evaluateStopping()
optimiser.evaluateStopping (metamodel, iteration, scores)
This function evaluates if the program needs to stop due to the score value or the iteration number.
Referenced by central().
gaInitialisePopulation()
optimiser.gaInitialisePopulation (model, metamodel)
This function create the initial random karyotype for the genetic algorithm.
References linearVariation(), and logarithmicVariation().
Referenced by central().
gaNaturalSelection()
optimiser.gaNaturalSelection (karyotype, iteration, scores, metamodel, outputfiles)
This function selects the best fit elements from the last generation karyotype.
Referenced by central().
gaPopulationScoresObtainer()
optimiser.gaPopulationScoresObtainer (iteration, karyotype, metamodel, model, outputfiles)
This function evaluates the score of the karyotype by calling scoreObtainer function.
Special emphasis is given for the parallel code.
References parallel.currentProcessor(), evaluateIteration(), evaluateSolution(), parallel.mainProcessor(), parallel.receive(), parallel.receiveAny(), scoreObtainer(), parallel.send(), parallel.sendAll(), and parallel.totalProcessors().
Referenced by central().
gaPopulationScoresObtainerLocal()
optimiser.gaPopulationScoresObtainerLocal (iteration, karyotype, metamodel, model, outputfiles)
This function evaluates the fitness function for the hybridOnePhase algorithm.
For each element it launches a local search algorithm and takes as fitness function value the result of the local optimisation.
References localOptimiser.central(), and evaluateIteration().
Referenced by central().
gaSex()
optimiser.gaSex (karyotype, bestChromosomes, sexChromosomes, model, metamodel)
This function directs the crossing over and mutation from one to the next generation.
References linearVariation(), and logarithmicVariation().
Referenced by central().
getSimulateValue()
optimiser.getSimulateValue (originalSimulationValues, node, target, model, metamodel)
This function retrieves the simulation value of a single node at a single time point.
linearVariation()
optimiser.linearVariation (minimalValue, maximalValue)
This function generates a random value for a parameter explored in a linear scale range.
Referenced by central(), sampler.ClassSample.createRandomSetOfParameters(), gaInitialisePopulation(), gaSex(), and randomSearch().
logarithmicVariation()
optimiser.logarithmicVariation (minimalValue, maximalValue)
This function generates a random value for a parameter explored in a logarithmic
Referenced by central(), sampler.ClassSample.createRandomSetOfParameters(), gaInitialisePopulation(), gaSex(), and randomSearch().
normalVariationForInitialCondition()
optimiser.normalVariationForInitialCondition (metamodel, model)
This function variates the initial condition of the model based on a normal distribution.
Referenced by central(), and randomSearch().
randomSearch()
optimiser.randomSearch (metamodel, model, outputfiles)
This function evaluates the score of a new random point in the parameter space.
References linearVariation(), logarithmicVariation(), normalVariationForInitialCondition(), and scoreObtainer().
Referenced by central().
scoreObtainer()
optimiser.scoreObtainer (metamodel, model, outputfiles)
This function obtains the fitness function value given a model and the experimental target.
It involves the simulation of the model.
A set of target values are determined, with its corresponding importance, that is, the ponderation.
Then a set of corresponding values at the simulation are searched. Because at the corresponding time there are several simulation values, depending on the time step, the simulation value of the earlier data point is taken. 
The values are substracted from one list to the other.
References centralFunctions.octaveIntegration(), centralFunctions.pythonIntegration(), and simulator.setIntegrationOption().
Referenced by sampler.ClassSample.calculateFitnessFunction(), surface.central(), central(), fitnessFunctionEvaluator.central(), gaPopulationScoresObtainer(), localOptimiser.pcalcr(), and randomSearch().
storeSolution()
optimiser.storeSolution (score, metamodel, model, workingDirectory)
This function saves a solution in the tags or SBML format.
References sbmlWorker.sbmlWriter().
Referenced by evaluateSolution().