cluster Namespace Reference
Functions
 dataTransformer (metamodel, outputfiles)
 defaultRunner (clusteringRange, metamodel, outputfiles)
 main (metamodel, outputfiles)
 octaveCodeWriter (metamodel, outputfiles)
 octaveExecuter (outputfiles)
 plotter (outputfiles, dimension, labels)
 resolutionChecker (metamodel, outputfiles)
 surfacePlotter (outputfiles, labels)
 volumePlotter (outputfiles, labels)
Function Documentation
dataTransformer()
cluster.dataTransformer (metamodel, outputfiles)
This function converts the data points to the adequate scale.
Referenced by main(), and resolutionChecker().
defaultRunner()
cluster.defaultRunner (clusteringRange, metamodel, outputfiles)
This function runs the clustering for the defined range of resolution values.
References octaveCodeWriter(), and octaveExecuter().
Referenced by main().
main()
cluster.main (metamodel, outputfiles)
This is the main function for the cluster algorithm.
This function directs the flow of algorithm.
References dataTransformer(), defaultRunner(), octaveCodeWriter(), octaveExecuter(), plotter(), and resolutionChecker().
Referenced by central.runner().
octaveCodeWriter()
cluster.octaveCodeWriter (metamodel, outputfiles)
This function writes the a simple code of octave to call the clustering algorithm.
Referenced by defaultRunner(), and main().
octaveExecuter()
cluster.octaveExecuter (outputfiles)
This function executes the octave code for clustering.
Referenced by defaultRunner(), and main().
plotter()
cluster.plotter (outputfiles, dimension, labels)
This function plots the results of the clustering.
References surfacePlotter(), and volumePlotter().
Referenced by main().
resolutionChecker()
cluster.resolutionChecker (metamodel, outputfiles)
This function defines different resolution bandwidths and run the clustering for each value.
The results are analysed
References dataTransformer().
Referenced by main().
surfacePlotter()
cluster.surfacePlotter (outputfiles, labels)
This function creates a plot of the clusters in 2D. Based on sampler.plot2D
Referenced by plotter().
volumePlotter()
cluster.volumePlotter (outputfiles, labels)
This function creates a plot of the clusters in 3D. Based on sampler.plot3D
Referenced by plotter().