#
#  Project: ByoDyn
#
#  Copyright (C) 2008 Alex Gomez-Garrido, Adrian L. Garcia-Lomana and Jordi Villa-Freixa
#
#  Author: Alex Gomez-Garrido
#
#  Created: 2007-03-08 by Alex Gomez-Garrido
#
#  This application is free software; you can redistribute it and/or
#  modify it under the terms of the GNU General Public
#  License as published by the Free Software Foundation; either
#  version 2 of the License, or (at your option) any later version.
#
#  This application is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#  Library General Public License for more details.
#
#  You should have received a copy of the GNU General Public
#  License along with this library; if not, write to the Free
#  Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111 USA.
# 

# $Id: fitnessFunctionEvaluator.py,v 4.3 2008/12/03 16:37:38 alglomana Exp $

## \file
# This module calculates the fitness function value given an experimental data set for a specific model.

import optimiser, simulator, initiator

def central(model, metamodel, outputfiles):
    
    '''
    The function checks for the compatibility of the simulation options and inserts a specified parameter value if it is the case, 
    it checks that the data points correspond to the simulation time, 
    it checks the target nodes and finally evaluates the fitness function.
    '''
    
    simulator.compatibilityChecker(metamodel, model)
    optimiser.checkDataPoints(model, metamodel)
    optimiser.checkTargetNodes(model, metamodel)
    score = optimiser.scoreObtainer(metamodel, model, outputfiles)
    scoreWriter(score, outputfiles)
    print 'The fitness function value is %s' %score

    return None

def scoreWriter(score, outputfiles):

    '''
    This function writes in the log file the score obtained for the fitness function evaluation.
    '''

    f = open(outputfiles.logFile, 'w')
    f.write('#/\n#/ generated by ByoDyn version %s\n#/\n'%initiator.BYODYNVERSION)
    f.write('Fitness function value is %s'%score)
    f.close()
    
    return None
